
#Commands
# pa create
# pa destroy
# pa select
# pa unselect
# pa visible [true/false]
# pa showbase [true/false]
# pa gravity [true/false]
# pa showarms [true/flase]
# pa torso [degrees]
# pa leftarm [degrees]
# pa rightarm [degrees]
# pa leftleg [degrees]
# pa rightleg [degrees]
# pa move [x] [y] [z]
# pa showname [true/flase]
# pa small [true/flase]
# pa summon
# pa copy
# pa paste
# pa body [degrees]
# pa setname [name]
# pa help [command?]
# pa reload

# posablearmorstands.use (select, unselect, help, reload)
# posablearmorstands.pose (showbase, leftarm, rightarm, leftleg, rightleg, torso, showarms)
# posablearmorstands.gravity (gravity)
# posablearmorstands.visible (visibible)
# posablearmorstands.move (move, position)
# posablearmorstands.create (create, destroy)
# posablearmorstands.name (showname, setname)
# posablearmorstands.small (small)
# posablearmorstands.copy (copy, paste)


parameter-two-tf-list:
  - 'true'
  - 'false'

parameter-two-degree-list:
  - '[# degrees 1-360 or -1]'

parameter-two-move-list: '[# >0 and <={0}]'

parameter-text-list:
  - '[text of name]'

create:
  default-elevation: 0.0
  default-distance: 2.0

move:
  distance-limit: 1.0

select:
  distance: 8

illegal-words-list:
  - bitch
  - dick
  - fag
  - nigger
  - homo
