
#Commands
# pa body [degrees]
# pa copy
# pa create
# pa destroy
# pa gravity [true/false]
# pa head [degrees]
# pa help [command?]
# pa leftarm [degrees]
# pa leftleg [degrees]
# pa move [x] [y] [z]
# pa paste pa select
# pa reload
# pa rightarm [degrees]
# pa rightleg [degrees]
# pa select
# pa setname
# pa showarms [true/flase]
# pa showbase [true/false]
# pa showname [true/flase]
# pa small [true/flase]
# pa summon
# pa torso [degrees]
# pa unselect
# pa visible [true/false]

# posablearmorstands.pose (select, unselect, showarms, leftarm, rightarm, leftleg, rightleg, torso, head, help)
# posablearmorstands.gravity (gravity)
# posablearmorstands.visible (visible, showbase)
# posablearmorstands.move (move, position)
# posablearmorstands.create (create, destroy)
# posablearmorstands.name (showname, setname)
# posablearmorstands.small (small)
# posablearmorstands.copy (copy, paste)
# posablearmorstands.admin (reload)


parameter-two-tf-list:
  - 'true'
  - 'false'

parameter-two-degree-list:
  - '[# degrees 1-360 or -1]'

parameter-two-move-list: '[# >0 and <={0}]'

parameter-text-list:
  - '[text of name]'

create:
  default-elevation: 0.0
  default-distance: 2.0
  auto-select: true

move:
  distance-limit: 1.0

select:
  distance: 8

illegal-words-list:
  - bitch
  - dick
  - fag
  - nigger
  - homo
